[general]
import = ['~/.dotfiles/alacritty-colors/doom-one.toml']

[cursor]
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
family = "Cousine for Powerline"

[scrolling]
history = 0

[window]
decorations = "none"
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 1
