#!/bin/sh
#
# fluxbox startup-script:

# Change your keymap:
xmodmap "$HOME/.Xmodmap"

# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# conky -d

# xfce4-power-manager, tray applet to show battery status
# xfce4-power-manager

# nm-applet, tray applet for managing networks
# nm-applet &

# start syndaemon to disable the touchpad while typing
syndaemon -k -i 0.3 -d

# xbanish hides cursor when typing: use ~/.dotfiles/get-xbanish.sh
xbanish &


which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi
exec fluxbox # -log "$HOME/.fluxbox/log"
